### ISSUE TITLE
ask about Saga

### ISSUE THREAD

**Issue by fizz12344321** [viniciusnrgarcia/saga-microservice-pattern#1]
Hi, i am reading your project and I love it. But i have a question, what queue do you use for the message queue, how do you manage the state of each service and how do you tackle and implement "Transaction outbox ". Thank u so much

**Comment by viniciusnrgarcia** [comment]
Hi, I'm using the RabbitMQ queue. The implementation is a test using the Saga pattern with choreography. Each service will be responsible for its event status. The microservice order readmefile has more information.
